name: Publish

on:
  release:
  workflow_dispatch:

env:
  FORCE_COLOR: 3

jobs:
  dist:
    name: Distribution build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hynek/build-and-inspect-python-package@v2

  test-publish:
    needs: [dist]
    name: Publish to TestPyPI
    environment: testpypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Remember to tell (test-)pypi about this repo before publishing
          repository-url: https://test.pypi.org/legacy/
