name: Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.13"]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        include:
          # The Macos and Windows jobs fail with 3.7 so just test on Linux
          - runs-on: ubuntu-latest
            python-version: "3.7"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.29"

      - name: Install package
        run: uv pip install --system -e .[dev]

      - name: Test package
        run: pytest --cov --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
