name: Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.13"]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv (Unix)
        if: runner.os != 'Windows'
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install uv (Windows)
        if: runner.os == 'Windows'
        run: powershell -c "irm https://astral.sh/uv/install.ps1 | iex"

      - name: Install package
        run: uv pip install --system "harmonwig[dev] @ ."

      - name: Test package
        run: pytest -ra --cov --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
